Revert "Revert "Merge pull request #19 from rpatel3001/soapy""
This reverts commit e6170ff730e17647a1f7eed0839d6345541e997c.

diff --git a/rootfs/etc/templates/run b/rootfs/etc/templates/run
--- a/rootfs/etc/templates/run
+++ b/rootfs/etc/templates/run
@@ -13,17 +13,11 @@ set -e
 
 ACARS_BIN="/usr/local/bin/acarsdec"
 # shellcheck disable=SC2001
+SOAPYSDR=""
 
-mapfile -t RTL_TEST_OUTPUT < <(timeout 1s rtl_test -d 0 2>&1 | grep -P '^\s+\d+:\s.*?,.*?,\s+SN:\s+.*?$' | IFS=$'\n' sed -n 's/^\s*\([^:]*\):[^,]*,[^,]*,\s*SN:\s*\(.*\)$/\1,\2/; s/\s*$//p' || true)
-for RTL_TEST_OUTPUT_LINE in "${RTL_TEST_OUTPUT[@]}"; do
-        if [[ "${RTL_TEST_OUTPUT_LINE##*,}" == "$SERIAL" ]]; then
-		DEVICE_ID="${RTL_TEST_OUTPUT_LINE%%,*}"
-	fi
-done
-
-if [[ -z "${DEVICE_ID}" ]]; then
-        echo "Could not find Device ID for serial '$SERIAL'"
-        exit 1
+if ! SoapySDRUtil --probe="${SOAPYSDR}"; then
+    echo "Could not find SoapySDR device for '$SOAPYSDR'"
+    exit 1
 fi
 
 FREQ_STRING=""
@@ -35,6 +29,10 @@ else
 fi
 
 ACARS_CMD=("-g" "$GAIN" "-i" "$FEED_ID")
+
+if [ -n "${CENTER_FREQ}" ]; then
+	ACARS_CMD+=("-c" "$CENTER_FREQ")
+fi
 
 if [ -n "${PPM}" ]; then
 	ACARS_CMD+=("-p" "$PPM")
@@ -52,6 +50,10 @@ if [ -n "${RTLMULT}" ]; then
 	ACARS_CMD+=("-m" "$RTLMULT")
 fi
 
+if [ -n "${VERBOSE}" ]; then
+	ACARS_CMD+=("-v")
+fi
+
 # Send output JSON to acars_server
 if [ -n "${SERVER}" ]; then
 	if [[ "${MODE}" == @(J|j) ]]; then
@@ -63,9 +65,9 @@ if [ -n "${SERVER}" ]; then
 	fi
 fi
 
-# Specify device ID
-if [ -n "${DEVICE_ID}" ]; then
-	ACARS_CMD+=("-r" "$DEVICE_ID")
+# Specify SOAPYSDR
+if [ -n "${SOAPYSDR}" ]; then
+	ACARS_CMD+=("-d" "$SOAPYSDR")
 fi
 
 # shellcheck disable=SC2206
